version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env.docker
    volumes:
      - .:/app

volumes:
  postgres_data:
